var API=['https://script.google.com/macros/s/',
'AKfycbwBoFSrUNHBmZq5c06zBzghgKr5T6SVLjLDJyuqoiv7CFOfQR7KofayIEU7oHc7_tw1',
'/exec'].join('');
var APP={t:null,g:null,gr:null,al:[],mi:-1};
function ir(id){document.querySelectorAll('.screen').forEach(function(s){s.classList.remove('active')});document.getElementById(id).classList.add('active');window.scrollTo(0,0)}
function toast(m,d){if(!d)d=2400;var t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(function(){t.classList.remove('show')},d)}
function ini(n){return n.split(' ').slice(0,2).map(function(p){return p[0]}).join('').toUpperCase()}
function hoy(){var d=new Date();var dias=['Domingo','Lunes','Martes','Miercoles','Jueves','Viernes','Sabado'];var meses=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'];return dias[d.getDay()]+' '+d.getDate()+' de '+meses[d.getMonth()]+' de '+d.getFullYear()}
function callApi(ac,params){var u=new URL(API);u.searchParams.set('accion',ac);if(params){Object.keys(params).forEach(function(k){u.searchParams.set(k,typeof params[k]==='object'?JSON.stringify(params[k]):params[k])})}return fetch(u.toString()).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json()})}
function doLogin(){var u=document.getElementById('iu').value.trim();var p=document.getElementById('ip').value.trim();var err=document.getElementById('le');var txt=document.getElementById('ltx');var spin=document.getElementById('lsp');if(!u||!p){err.textContent='Escribe usuario y contrasena';err.classList.add('show');return}err.classList.remove('show');txt.style.display='none';spin.style.display='block';callApi('login',{usuario:u,password:p}).then(function(res){spin.style.display='none';txt.style.display='block';if(res.ok){APP.t=res.tutora;document.getElementById('hav').textContent=ini(res.tutora.nombre.replace('Mtra.','').trim());document.getElementById('hf').textContent=new Date().toLocaleDateString('es-MX',{day:'2-digit',month:'short'});document.getElementById('fb2').textContent=hoy();var sel=document.getElementById('ranio');var anio=new Date().getFullYear();[anio-1,anio].forEach(function(a){var o=document.createElement('option');o.value=String(a);o.textContent=String(a);if(a===anio)o.selected=true;sel.appendChild(o)});document.getElementById('rmes').value=String(new Date().getMonth()+1).padStart(2,'0');ir('ss')}else{err.textContent=res.error||'Credenciales incorrectas';err.classList.add('show')}}).catch(function(e){spin.style.display='none';txt.style.display='block';err.textContent='Error: '+e.message;err.classList.add('show')})}
function selG(g){APP.g=g;APP.gr=null;document.getElementById('sr2').style.display='none';document.getElementById('bpl').style.display='none';document.querySelectorAll('#cg .chip').forEach(function(c){c.classList.toggle('sel',c.textContent.trim().startsWith(g.replace('o','')))});document.getElementById('cgr').innerHTML=['A','B','C','D','E','F'].map(function(x){return'<div class="chip" onclick="selGr(\'' +x+ '\')">' +x+ '</div>'}).join('')}
function selGr(g){APP.gr=g;document.querySelectorAll('#cgr .chip').forEach(function(c){c.classList.toggle('sel',c.textContent===g)});callApi('getAlumnas',{grado:APP.g,grupo:APP.gr}).then(function(r){document.getElementById('srt').textContent=APP.g+' '+APP.gr+(r.ok?' - '+r.alumnas.length+' alumnas':'')}).catch(function(){document.getElementById('srt').textContent=APP.g+' '+APP.gr});document.getElementById('sr2').style.display='block';document.getElementById('bpl').style.display='block'}
function goLista(){if(!APP.g||!APP.gr)return;callApi('getAlumnas',{grado:APP.g,grupo:APP.gr}).then(function(r){if(!r.ok){toast('Error');return}APP.al=r.alumnas.map(function(a){return{id:a.id,nombre:a.nombre,estado:'Presente',justificada:false,comentario:''}});return callApi('verificarAsistenciaHoy',{grado:APP.g,grupo:APP.gr}).then(function(v){if(v.ok&&v.registrada){v.registros.forEach(function(rec){var a=APP.al.find(function(x){return x.nombre===rec.nombre});if(a)a.estado=rec.estado});toast('Ya se tomo lista hoy.')}document.getElementById('ltit').textContent=APP.g+' '+APP.gr+' Lista';document.getElementById('lsub').textContent=new Date().toLocaleDateString('es-MX');renderL();ir('slista')})}).catch(function(e){toast('Error: '+e.message)})}
function renderL(){var c=document.getElementById('alist');c.innerHTML='';APP.al.forEach(function(a,i){var cl={Presente:'presente',Ausente:'ausente',Retardo:'retardo'};var ic={Presente:'P',Ausente:'A',Retardo:'R'};var badge='';if(a.estado==='Ausente')badge=a.justificada?'<span class="bj">Justificada</span>':'<span style="color:var(--r);font-size:11px">Sin justificar</span>';else if(a.comentario)badge='<span style="font-size:11px;color:var(--g3)">'+a.comentario.slice(0,30)+'</span>';var row=document.createElement('div');row.className='ar '+cl[a.estado];row.innerHTML='<div class="cc">'+ic[a.estado]+'</div><div class="ai"><div class="an">'+a.nombre+'</div>'+(badge?'<div class="ab">'+badge+'</div>':'')+'</div><button class="bd" onclick="abrirM('+i+',event)">...</button>';row.addEventListener('click',function(e){if(e.target.closest('.bd'))return;togA(i)});c.appendChild(row)});cntrs()}
function togA(i){var a=APP.al[i];if(a.estado==='Presente'){a.estado='Ausente';a.justificada=false}else if(a.estado==='Ausente'){a.estado='Presente';a.justificada=false}else a.estado='Presente';renderL()}
function cntrs(){var p=APP.al.filter(function(a){return a.estado==='Presente'}).length;var au=APP.al.filter(function(a){return a.estado==='Ausente'}).length;var j=APP.al.filter(function(a){return a.estado==='Ausente'&&a.justificada}).length;var r=APP.al.filter(function(a){return a.estado==='Retardo'}).length;var tot=APP.al.length;['cp','ca','cj','cr'].forEach(function(id,idx){document.getElementById(id).textContent=[p,au,j,r][idx]});document.getElementById('lcnt').textContent=p+'/'+tot;document.getElementById('pf').style.width=(tot>0?(p/tot*100):0)+'%'}
function abrirM(i,e){if(e)e.stopPropagation();APP.mi=i;var a=APP.al[i];document.getElementById('mav').textContent=ini(a.nombre);document.getElementById('mnom').textContent=a.nombre;document.getElementById('mgru').textContent=APP.g+' '+APP.gr;document.getElementById('mcom').value=a.comentario||'';setEB(a.estado);setJB(a.justificada);document.getElementById('sj').style.display=a.estado==='Ausente'?'block':'none';document.getElementById('mo').classList.add('open')}
function closeM(e){if(e&&e.target!==document.getElementById('mo'))return;document.getElementById('mo').classList.remove('open')}
function setE(s){if(APP.mi<0)return;APP.al[APP.mi].estado=s;if(s!=='Ausente')APP.al[APP.mi].justificada=false;setEB(s);document.getElementById('sj').style.display=s==='Ausente'?'block':'none'}
function setJ(v){if(APP.mi<0)return;APP.al[APP.mi].justificada=v;setJB(v)}
function setEB(s){document.getElementById('ep').className='e'+(s==='Presente'?' sp':'');document.getElementById('ea').className='e'+(s==='Ausente'?' sa':'');document.getElementById('ere').className='e'+(s==='Retardo'?' sr':'')}
function setJB(v){document.getElementById('jsi').className='j'+(v?' sel':'');document.getElementById('jno').className='j'+(!v?' sel':'')}
function saveDet(){if(APP.mi<0)return;APP.al[APP.mi].comentario=document.getElementById('mcom').value.trim();document.getElementById('mo').classList.remove('open');renderL();toast('Guardado')}
function doGuardar(){var btn=document.getElementById('bg');btn.disabled=true;btn.textContent='Guardando...';var payload={tutoraId:APP.t.id,tutoraNombre:APP.t.nombre,grado:APP.g,grupo:APP.gr,registros:APP.al.map(function(a){return{alumnoId:a.id,alumnoNombre:a.nombre,estado:a.estado,justificada:a.justificada,comentario:a.comentario}})};callApi('guardarAsistencia',{payload:JSON.stringify(payload)}).then(function(r){btn.disabled=false;btn.textContent='Guardar asistencia';if(r.ok){toast('Guardado: '+r.guardados+' alumnas',3000);setTimeout(function(){ir('ss')},1500)}else toast('Error: '+r.error)}).catch(function(e){btn.disabled=false;btn.textContent='Guardar asistencia';toast('Error: '+e.message)})}
function goRep(){ir('srep')}
function doRep(){var a=document.getElementById('ranio').value,m=document.getElementById('rmes').value,g=document.getElementById('rgrado').value,gr=document.getElementById('rgrupo').value;callApi('getReporteMes',{anio:a,mes:m,grado:g,grupo:gr}).then(function(r){if(!r.ok){toast('Error');return}document.getElementById('rpct').textContent=r.resumen.pctAsistencia+'%';document.getElementById('rau').textContent=r.resumen.ausentes;document.getElementById('rju').textContent=r.resumen.justificadas;document.getElementById('rre').textContent=r.resumen.retardos;document.getElementById('rtb').innerHTML=r.detalle.map(function(x){var cl=x.ausentes>=5?'pr':x.ausentes>=3?'pa':'pv';return'<tr><td>'+x.nombre+'</td><td style="text-align:center">'+x.presentes+'</td><td style="text-align:center"><span class="pl '+cl+'">'+x.ausentes+'</span></td><td style="text-align:center">'+x.justificadas+'</td></tr>'}).join('');var rr=document.getElementById('rres');rr.style.display='flex';rr.style.flexDirection='column';rr.style.gap='14px'}).catch(function(){toast('Error')})}
function doLogout(){APP.t=null;APP.al=[];document.getElementById('iu').value='';document.getElementById('ip').value='';ir('sl')}
document.getElementById('ip').addEventListener('keydown',function(e){if(e.key==='Enter')doLogin()});